# Author: Diego Garcia Huerta
# Contact: https://www.linkedin.com/in/diegogh/
#
# YOU SHOULD MERGE these entries into your engine_locations.yml config file, as
# THIS FILE BY ITSELF WILL NOT WORK
# These are the additions to get substancepainter engine up and running with the
# default tk-apps


# substancepainter
# Make sure to check for latest versions of the engine here and update the
# version section of the git description below accordingly.
# https://github.com/diegogarciahuerta/tk-substancepainter/releases
engines.tk-substancepainter.location:
  type: git
  path: https://github.com/diegogarciahuerta/tk-substancepainter
  version: v1.1.1
