# Author: Diego Garcia Huerta
# Contact: https://www.linkedin.com/in/diegogh/
#
# YOU SHOULD MERGE these entries into your frameworks.yml config file, as
# THIS FILE BY ITSELF WILL NOT WORK
# These are the additions to get substancepainter engine up and running with the
# default tk-apps


frameworks:
  # unrealqt - PySide build for Unreal (Windows-only)
  tk-framework-unrealqt_v1.x.x:
    location:
      version: v1.2.5
      type: github_release
      organization: vertpipe
      repository: tk-framework-unrealqt
