# Author: Diego Garcia Huerta
# Contact: https://www.linkedin.com/in/diegogh/
#
# YOU SHOULD MERGE these entries into your settings file, as
# THIS FILE BY ITSELF WILL NOT WORK
# These are the additions to get substancepainter engine up and running with the
# default tk-apps for this environment

settings.tk-multi-breakdown.substancepainter:
  hook_scene_operations: '{engine}/tk-multi-breakdown/tk-substancepainter_scene_operations.py'
  location: "@apps.tk-multi-breakdown.location"
